In [1]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [3]:
l = ["A 21", "C 22", "D 12", "A 31"]

sorted(l)

['A 21', 'A 31', 'C 22', 'D 12']

In [6]:
sorted(l, key = lambda x: x.split()[-1])

['D 12', 'A 21', 'C 22', 'A 31']

In [7]:
sort_key = lambda x: x.split()[-1]
sorted(l, key = sort_key)

['D 12', 'A 21', 'C 22', 'A 31']

In [12]:
import random as rnd 

dices = [rnd.randint(1,6) for _ in range(10)]
dices

[6, 5, 3, 4, 5, 2, 5, 4, 5, 6]

In [13]:
import numpy as np 

x = np.random.randint(1,7,10)
x

array([5, 1, 4, 2, 2, 3, 3, 4, 6, 2])

In [14]:
x**2

array([25,  1, 16,  4,  4,  9,  9, 16, 36,  4])

In [23]:
dice1 = np.arange(1, 7)
dice2 = np.arange(1, 7)
dice1.shape = (6,1)


dice1+dice2

array([[ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10, 11],
       [ 7,  8,  9, 10, 11, 12]])

In [19]:
dice1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [22]:
dice2.transpose()

array([1, 2, 3, 4, 5, 6])

In [27]:
dice1 = np.arange(1, 7).reshape(6,-1)
dice1 

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [29]:
np.ones(7),np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
p = input("Write two numbers separate with ,")
p = [float(number) for number in p.split(",")]
p


[4.0, 5.0]

In [5]:
# i andra språk använder man getters och setters 
class Person:
    
    # type hinting - returns None
    def __init__(self, age: float) -> None:
        # bare attribute
        self._age = age

    def get_age(self) -> float:
        return self._age
    
    def set_age(self, value: float) -> None:
        # valideringskod
        self._age = value

person_instance = Person(40)
#person_instance.age = -5
print(person_instance.get_age())

person_instance.set_age(10)
person_instance.get_age()


40


10

In [17]:
# i Python vill man direkt komma åt ens property och då dekorerar med med @property

class Person:
    
    # type hinting - returns None
    def __init__(self, age: float) -> None:
        # assignment -> setter körs
        self.age = age

    @property
    def age(self) -> float:
        print("getter called ...")
        return self._age
    
    # andra metoder ...
    def run_away(self):
        print("Person runs away from class ...")

    @age.setter
    def age(self, value: float) -> None:
        # valideringskod

        print("Setter called ...")
        self._age = value

person_instance = Person(40)
person_instance.age = 20
person_instance.age

Setter called ...
Setter called ...
getter called ...


20

In [12]:
person_instance1 = Person(200)
print(person_instance1.__dict__)
person_instance1._age

Setter called ...
{'_age': 200}


200

In [13]:
Person()

TypeError: __init__() missing 1 required positional argument: 'age'

In [16]:
class Person:
    
    # type hinting - returns None
    def __init__(self, age: float) -> None:
        
        self.age = age

person2 = Person(4)
person2


In [15]:
class A: 
    def __eq__(self, other):
        print(f"__eq__() från A")

class B(A): 
    def __eq__(self, other):
        print("__eq__() från B")

class C(B):
    def __eq__(self, other):
        A().__eq__(other)


c1 = C()
c2 = C()

c1==c2



__eq__() från A, C
